products = [
    {
        '_id': '1',
        'name': 'Kamera',
        'image': '/images/kamera.png',
        'description':
            'kamera DoLorem Ipsum is simply dummy text of the printing and typesetting industry. L',
        'brand': 'Suntalam',
        'category': 'Ev',
        'price': 89.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'airpods',
        'image': '/images/airpods.png',
        'description':
            'airpods  Ipsum is simply dummy text of the printing and typesetting industry. L',
        'brand': 'Apple',
        'category': 'Elektronik',
        'price': 599.99,
        'countInStock': 0,
        'rating': 4.0,
        'numReviews': 8,
    },
    {
        '_id': '3',
        'name': 'bilgisayar',
        'image': '/images/bilgisayar.png',
        'description':
            'Ipsum is simply dummy text of the printing and typesetting industry. L',
        'brand': 'Asus',
        'category': 'Elektronik',
        'price': 929.99,
        'countInStock': 5,
        'rating': 3,
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'kulaklık',
        'image': '/images/kulaklik1.png',
        'description':
            'Ipsum is simply dummy text of the printing and typesetting industry. L',
        'brand': 'Sony',
        'category': 'Elektronik',
        'price': 399.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '5',
        'name': 'kulaklık 2',
        'image': '/images/kulaklik2.png',
        'description':
            'Ipsum is simply dummy text of the printing and typesetting industry. L',
        'brand': 'Sony',
        'category': 'Elektronik',
        'price': 49.99,
        'countInStock': 7,
        'rating': 3.5,
        'numReviews': 10,
    },
    {
        '_id': '6',
        'name': 'Laptop 1',
        'image': '/images/laptop.png',
        'description':
            'Ipsum is simply dummy text of the printing and typesetting industry. L',
        'brand': 'Laptop',
        'category': 'Taşınabilir',
        'price': 29.99,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
    },
    {
        '_id': '7',
        'name': 'kulaklık 3',
        'image': '/images/laptop.png',
        'description':
            'Ipsum is simply dummy text of the printing and typesetting industry. L',
        'brand': 'Sony',
        'category': 'Elektronik',
        'price': 49.99,
        'countInStock': 7,
        'rating': 3.5,
        'numReviews': 10,
    },
    {
        '_id': '8',
        'name': 'Laptop 1',
        'image': '/images/laptop2.png',
        'description':
            'Ipsum is simply dummy text of the printing and typesetting industry. L',
        'brand': 'Laptop',
        'category': 'Taşınabilir',
        'price': 29.99,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
    },
]
